# Generated by Django 3.1.7 on 2021-04-29 09:45

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20210428_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('GL', 'Grand Landscape'), ('IA', 'Intimate and Abstract'), ('N', 'Nightscape'), ('A', 'Aerial')], default='GL', max_length=128, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=django_thumbs.db.models.ImageWithThumbsField(default='entries/default-entry.png', upload_to='entries/'),
        ),
    ]
