# Generated by Django 3.1.7 on 2021-04-29 09:58

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20210429_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=thumbnails.fields.ImageField(default='entries/default-entry.png', upload_to='entries/', verbose_name='Entry Photo'),
        ),
    ]
