# Generated by Django 3.1.7 on 2021-05-02 23:04

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=thumbnails.fields.ImageField(default='entries/default-entry.png', max_length=500, upload_to='entries/', verbose_name='Entry Photo'),
        ),
    ]
