# Generated by Django 3.1.7 on 2021-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20210510_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='photo_stats',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Photo Stats'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Thumbnail URL'),
        ),
    ]
