# Generated by Django 3.1.7 on 2021-05-10 11:35

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0008_auto_20210510_0918'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='fullsize_url',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='photo_stats',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('GL', 'Grand Landscape'), ('IA', 'Intimate and Abstract'), ('N', 'Nightscape'), ('A', 'Aerial')], default='GL', max_length=128, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
