# Generated by Django 3.1.7 on 2021-05-10 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0009_auto_20210510_1135'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='fullsize_url',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Fullsize URL'),
        ),
        migrations.AddField(
            model_name='entry',
            name='photo_stats',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Photo Stats'),
        ),
        migrations.AddField(
            model_name='entry',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('GL', 'Grand Landscape'), ('IA', 'Intimate and Abstract'), ('N', 'Nightscape'), ('A', 'Aerial'), ('P1', 'Portfolio One'), ('P2', 'Portfolio Two')], default='GL', max_length=128, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
