# Generated by Django 3.1.7 on 2021-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_auto_20210510_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(default='entries/default-entry.png', max_length=500, upload_to='entries/', verbose_name='Photo'),
        ),
    ]
