# Generated by Django 3.1.7 on 2021-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_auto_20210602_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ef1_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='EF1 Filename'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ef2_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='EF2 Filename'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ef3_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='EF3 Filename'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ef4_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='EF4 Filename'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ef5_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='EF5 Filename'),
        ),
        migrations.AddField(
            model_name='entry',
            name='evidence_file_1',
            field=models.FileField(default='raws/default-entry.png', upload_to='raws/', verbose_name='Evidence #1'),
        ),
        migrations.AddField(
            model_name='entry',
            name='evidence_file_2',
            field=models.FileField(default='raws/default-entry.png', upload_to='raws/', verbose_name='Evidence #2'),
        ),
        migrations.AddField(
            model_name='entry',
            name='evidence_file_3',
            field=models.FileField(default='raws/default-entry.png', upload_to='raws/', verbose_name='Evidence #3'),
        ),
        migrations.AddField(
            model_name='entry',
            name='evidence_file_4',
            field=models.FileField(default='raws/default-entry.png', upload_to='raws/', verbose_name='Evidence #4'),
        ),
        migrations.AddField(
            model_name='entry',
            name='evidence_file_5',
            field=models.FileField(default='raws/default-entry.png', upload_to='raws/', verbose_name='Evidence #5'),
        ),
        migrations.AddField(
            model_name='entry',
            name='in_book',
            field=models.BooleanField(blank=True, default=False, max_length=1024, verbose_name='In Book'),
        ),
        migrations.AddField(
            model_name='entry',
            name='in_second_round',
            field=models.BooleanField(default=False, verbose_name='In Second Round'),
        ),
        migrations.AddField(
            model_name='entry',
            name='passed_checks',
            field=models.BooleanField(blank=True, default=False, max_length=1024, verbose_name='Passed Checks'),
        ),
    ]
