# Generated by Django 3.1.7 on 2022-04-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20210829_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='ef1_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='IV1 Filename'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ef2_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='IV2 Filename'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ef3_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='IV3 Filename'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ef4_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='IV4 Filename'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ef5_filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='IV5 Filename'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evidence_file_1',
            field=models.FileField(blank=True, default='raws/default-entry.png', null=True, upload_to='raws/', verbose_name='Verification #1'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evidence_file_2',
            field=models.FileField(blank=True, default='raws/default-entry.png', null=True, upload_to='raws/', verbose_name='Verification #2'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evidence_file_3',
            field=models.FileField(blank=True, default='raws/default-entry.png', null=True, upload_to='raws/', verbose_name='Verification #3'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evidence_file_4',
            field=models.FileField(blank=True, default='raws/default-entry.png', null=True, upload_to='raws/', verbose_name='Verification #4'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='evidence_file_5',
            field=models.FileField(blank=True, default='raws/default-entry.png', null=True, upload_to='raws/', verbose_name='Verification #5'),
        ),
    ]
