# Generated by Django 3.1.7 on 2022-05-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_auto_20220425_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('GS', 'Grand Scenic'), ('IL', 'Intimate Landscapes'), ('AD', 'Abstracts & Details')], default='GS', max_length=128, null=True, verbose_name='Category'),
        ),
    ]
