# Generated by Django 3.1.7 on 2023-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0016_auto_20220531_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='special_award',
            field=models.CharField(blank=True, choices=[('CP', 'Common Places'), ('M', 'Mountains'), ('W', 'Water Worlds'), ('BW', 'Black and White'), ('N', 'Nightscape'), ('E', 'Environmental'), ('A', 'Aerial')], default='', max_length=128, null=True, verbose_name='Special Award'),
        ),
    ]
