# Generated by Django 3.1.7 on 2023-05-22 16:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_entry_special_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='special_award',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CP', 'Common Places'), ('M', 'Mountains'), ('W', 'Water Worlds'), ('BW', 'Black and White'), ('N', 'Nightscape'), ('E', 'Environmental'), ('A', 'Aerial')], default='', max_length=256, null=True, verbose_name='Special Award'),
        ),
    ]
