# Generated by Django 3.1.7 on 2024-04-05 10:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_auto_20230529_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='special_award',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('EW', 'Environmental Wildlife'), ('CI', 'Creative Icon'), ('CP', 'Common Places'), ('M', 'Mountains'), ('W', 'Water Worlds'), ('BW', 'Black and White'), ('N', 'Nightscape'), ('E', 'Environmental'), ('A', 'Aerial')], default='', max_length=256, null=True, verbose_name='Special Award (<a href="https://naturallandscapeawards.com/categories#special_awards" target="_blank">more info</a>)'),
        ),
    ]
