# Generated by Django 3.1.7 on 2021-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20210327_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Facebook',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Short Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marketing_prefs',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Marketing Preferences'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='State/Region/County'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Main Website'),
        ),
    ]
