# Generated by Django 3.1.7 on 2021-05-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20210418_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_status',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Payment Status'),
        ),
    ]
