# Generated by Django 3.1.7 on 2021-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_customuser_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_plan',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Payment Status'),
        ),
    ]
