# Generated by Django 3.1.7 on 2021-05-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_customuser_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_young_entrant',
            field=models.CharField(blank=True, default='False', max_length=1024, verbose_name='Is Young Entrant'),
        ),
    ]
