# Generated by Django 3.1.7 on 2021-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_customuser_is_young_entrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projecty_description_one',
            field=models.TextField(blank=True, null=True, verbose_name='Project Description One'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='projecty_description_two',
            field=models.TextField(blank=True, null=True, verbose_name='Project Description Two'),
        ),
    ]
