# Generated by Django 3.1.7 on 2021-06-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_auto_20210602_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='projecty_description_one',
            new_name='project_description_one',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='projecty_description_two',
            new_name='project_description_two',
        ),
    ]
