# Generated by Django 3.1.7 on 2021-06-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_auto_20210605_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='project_title_one',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Project Title One'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='project_title_two',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Project Title Two'),
        ),
    ]
