# Generated by Django 3.1.7 on 2022-04-27 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_auto_20210608_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Facebook'),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Competition Year')),
                ('payment_status', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Payment Status')),
                ('payment_plan', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Payment Plan')),
                ('payment_upgrade_status', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Payment Upgrade Status')),
                ('payment_upgrade_plan', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Payment Upgrade Plan')),
                ('is_young_entrant', models.CharField(blank=True, default='False', max_length=1024, verbose_name='Is Young Entrant')),
                ('project_title_one', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Project Title One')),
                ('project_description_one', models.TextField(blank=True, null=True, verbose_name='Project Description One')),
                ('project_title_two', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Project Title Two')),
                ('project_description_two', models.TextField(blank=True, null=True, verbose_name='Project Description Two')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
