# Generated by Django 3.1.7 on 2022-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_auto_20220427_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Facebook',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Twitter'),
        ),
    ]
