# Generated by Django 3.1.7 on 2022-05-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_auto_20220427_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Main Website'),
        ),
    ]
