# Generated by Django 3.1.7 on 2023-05-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0015_auto_20220531_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coupon',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Coupon'),
        ),
    ]
