# Generated by Django 3.1.7 on 2023-07-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_customuser_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_media_link',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Social Media Link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_media_type',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Social Media Type'),
        ),
    ]
