# Generated by Django 3.1.7 on 2023-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0017_auto_20230721_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Location'),
        ),
    ]
